### PR TITLE
add selectOne

### LINKED ISSUE #4: add selectOne
use `selectorQuery`

### PR DESCRIPTION
**Pull request by stoeffel**
closes #4

### CODE REVIEW

**Comment by hemanth** [comment]
@stoeffel This is awesome! (Now it's more like a race b/w you and me ;))

**Comment by stoeffel** [comment]
:smile:

**Comment by stoeffel** [comment]
@hemanth can you review? Or is it good to :ship:

**Comment by hemanth** [comment]
Looks good, please don't bump the version manually, rather use `npm version major/minor/patch` and then `git push --tags` :+1:

**Pull request merged**
